spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springstudy_db?useSSL=false&serverTimezone=Asia/Seoul&allowPubliKeyRetrieval=true&characterEncoding=UTF-8
    username: springstudy_user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        default_batch_fetch_size: 100
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace